### ISSUE TITLE
Why android29.jar? Stop supporting old devices.

### ISSUE THREAD

**Issue by Gaojianli** [ipid/my-system-app#1]
Just let them install Android 11.
https://github.com/Gaojianli/YATT/pull/1
![image](https://user-images.githubusercontent.com/19235246/84862568-fd100780-b0a5-11ea-870e-e44fbf187b00.png)

**Comment by ipid** [comment]
What are you talking about? android29.jar is just for Android 10.

**Comment by Gaojianli** [comment]
> What are you talking about? android29.jar is just for Android 10.



> What are you talking about? android29.jar is just for Android 10.

Android 11, api 30 please

**Comment by ipid** [comment]
> > What are you talking about? android29.jar is just for Android 10.
> 
> > What are you talking about? android29.jar is just for Android 10.
> 
> Android 11, api 30 please

But since https://github.com/anggrayudi/android-hidden-api didn't provide an android30.jar with `@hide` and `@UnsupportedAppUsage` removed, I can't update the jar version.
